services:
  - type: web
    name: sx-content-app
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 server_stdlib.py"
    envVars:
      - key: SX_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
